dist: focal
language: python
python:
- '3.8'
matrix:
  include:
  - name: "Bump master"
    env: BRANCH=master
  - name: "Bump ussuri"
    env: BRANCH=ussuri
  - name: "Bump train"
    env: BRANCH="train"
before_script:
- openssl aes-256-cbc -K $encrypted_83630750896a_key -iv $encrypted_83630750896a_iv
  -in travis_gerrit_key.enc -out /tmp/travis_gerrit_key -d && chmod 600 /tmp/travis_gerrit_key
- eval "$(ssh-agent -s)"
- ssh-add /tmp/travis_gerrit_key
script: ./bump.sh $BRANCH
